services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - '3080:3080'
    networks:
      - inventory
networks:
  inventory:
    external: true