services:
  inventory-api:
    container_name: inventory-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/inventory-api
    ports:
      - '3080:3080'
    networks:
      - inventory
networks:
  inventory:
    external: true