services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - '3080:3080'
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/db
  cache:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
  db:
    driver: local
