services:
  inventory-api:
    container_name: inventory-api
    build: .
    volumes:
      - .:/inventory-api
    ports:
      - "3001:3001"
    networks:
      - inventory
networks:
  inventory:
    driver: bridge
