POST http://localhost:3080/categories HTTP/1.1
Content-Type: application/json

{
  "name": "Brakes",
  "items": []
}

###

POST http://localhost:3080/items HTTP/1.1
Content-Type: application/json

{
  "name": "WX50",
  "category": "685995bf672f86acb680a5b4",
  "price": 500,
  "stock": 4,
  "description": "Brake pads for Ford vehicles"
}

###

PUT http://localhost:3080/items/685999c19749207e634bbcc2 HTTP/1.1
Content-Type: application/json

{
  "name": "Antifreeze",
  "price": 130,
  "stock": 20,
  "description": "Antifreeze for cars x2"
}

###

DELETE http://localhost:3080/items/68599a4e26aacc70c3685640 HTTP/1.1

