POST http://localhost:3080/categories HTTP/1.1
Content-Type: application/json

{
  "name": "Brakes",
  "items": []
}

###

POST http://localhost:3080/items HTTP/1.1
Content-Type: application/json

{
  "name": "WX50",
  "category": "6859738fdb6e22dfba2d5b33",
  "price": 500,
  "stock": 4,
  "description": "Brake pads for Nissan vehicles"
}

###

PUT http://localhost:3080/items/67e0a98daa462a267e153276 HTTP/1.1
Content-Type: application/json

{
  "name": "Antifreeze",
  "price": 130,
  "stock": 20,
  "description": "Antifreeze for cars x2"
}

###

DELETE http://localhost:3080/items/67ef42583a18fec27a8ba84e HTTP/1.1
